name: MON-S01 E2E Regression Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'modules/**'
      - 'parsers/**'
      - 'ocr/**'
      - 'normalizer/**'
      - 'storage/**'
      - 'tests/**'
      - '.github/workflows/mon_s01_e2e_ci.yml'
  
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'modules/**'
      - 'parsers/**'
      - 'ocr/**'
      - 'normalizer/**'
      - 'storage/**'
      - 'tests/**'
  
  schedule:
    # Каждый день в 6:00 UTC (для регрессионного мониторинга)
    - cron: '0 6 * * *'
  
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode (mock or real)'
        required: false
        default: 'mock'
        type: choice
        options:
          - mock
          - real

env:
  PYTHON_VERSION: '3.9'
  
jobs:
  mon-s01-e2e-regression:
    name: 'MON-S01 E2E Regression Suite'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        test_suite: [
          { name: 'Core E2E', pattern: 'test_mon_s01_e2e_regression.py' },
          { name: 'Evil Fixtures', pattern: 'test_mon_s01_fixtures.py', optional: true }
        ]
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Для diff анализа
      
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Cache test dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-e2e-${{ hashFiles('requirements.txt', 'requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-e2e-
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-html pytest-json-report
          
          # Основные зависимости проекта
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          
          # Тестовые зависимости
          if [ -f requirements-test.txt ]; then
            pip install -r requirements-test.txt
          fi
          
          # Минимальные зависимости для E2E тестов
          pip install pathlib typing-extensions
      
      - name: Create Evil Test Fixtures
        run: |
          echo "🧪 Создание Evil Test Fixtures..."
          python3 tests/fixtures/create_evil_fixtures_simple.py
          
          echo "📋 Проверка созданных fixtures:"
          ls -la tests/fixtures/evil_files/
          ls -la tests/fixtures/expected_outputs/
      
      - name: Run MON-S01 E2E Regression Tests
        id: e2e_tests
        run: |
          echo "🚀 Запуск MON-S01 E2E Regression Suite"
          
          # Определяем режим тестирования
          TEST_MODE="${{ github.event.inputs.test_mode || 'mock' }}"
          echo "Test mode: $TEST_MODE"
          
          # Создаем директории для отчетов
          mkdir -p tests/reports
          mkdir -p test-results
          
          # Запускаем E2E тесты
          if [[ "${{ matrix.test_suite.name }}" == "Core E2E" ]]; then
            echo "Запуск основных E2E тестов..."
            python3 tests/test_mon_s01_e2e_regression.py > test-results/e2e_output.log 2>&1
            E2E_EXIT_CODE=$?
            
            echo "E2E тесты завершены с кодом: $E2E_EXIT_CODE"
            
            # Также запускаем через pytest для дополнительных отчетов
            pytest tests/test_mon_s01_e2e_regression.py::TestMONS01E2ERegressionSuite::test_e2e_regression_full \
              -v --tb=short \
              --html=test-results/e2e_report.html \
              --json-report --json-report-file=test-results/e2e_pytest.json \
              || true
            
            # Сохраняем exit code для следующих шагов
            echo "e2e_exit_code=$E2E_EXIT_CODE" >> $GITHUB_OUTPUT
            
          else
            echo "Запуск дополнительных тестов fixtures..."
            # Дополнительные тесты (если есть)
            echo "e2e_exit_code=0" >> $GITHUB_OUTPUT
          fi
      
      - name: Parse E2E Results
        id: parse_results
        if: always()
        run: |
          echo "📊 Анализ результатов E2E тестов..."
          
          # Ищем последний отчет
          LATEST_REPORT=$(ls -t tests/reports/mon_s01_e2e_report_*.json 2>/dev/null | head -1)
          
          if [[ -f "$LATEST_REPORT" ]]; then
            echo "Найден отчет: $LATEST_REPORT"
            
            # Извлекаем ключевые метрики
            TOTAL_TESTS=$(jq -r '.summary.total_tests' "$LATEST_REPORT")
            PASSED_TESTS=$(jq -r '.summary.passed' "$LATEST_REPORT")
            FAILED_TESTS=$(jq -r '.summary.failed' "$LATEST_REPORT")
            PASS_RATE=$(jq -r '.summary.pass_rate' "$LATEST_REPORT")
            DURATION=$(jq -r '.summary.total_duration_sec' "$LATEST_REPORT")
            MOCK_MODE=$(jq -r '.mock_mode' "$LATEST_REPORT")
            
            echo "total_tests=$TOTAL_TESTS" >> $GITHUB_OUTPUT
            echo "passed_tests=$PASSED_TESTS" >> $GITHUB_OUTPUT
            echo "failed_tests=$FAILED_TESTS" >> $GITHUB_OUTPUT
            echo "pass_rate=$PASS_RATE" >> $GITHUB_OUTPUT
            echo "duration=$DURATION" >> $GITHUB_OUTPUT
            echo "mock_mode=$MOCK_MODE" >> $GITHUB_OUTPUT
            
            # Копируем отчет в test-results
            cp "$LATEST_REPORT" test-results/e2e_detailed_report.json
            
            echo "📈 Результаты:"
            echo "  Всего тестов: $TOTAL_TESTS"
            echo "  Пройдено: $PASSED_TESTS"
            echo "  Провалено: $FAILED_TESTS"
            echo "  Процент успеха: $PASS_RATE%"
            echo "  Время выполнения: ${DURATION}s"
            echo "  Mock режим: $MOCK_MODE"
            
          else
            echo "⚠️ Отчет E2E тестов не найден"
            echo "total_tests=0" >> $GITHUB_OUTPUT
            echo "passed_tests=0" >> $GITHUB_OUTPUT
            echo "failed_tests=1" >> $GITHUB_OUTPUT
            echo "pass_rate=0" >> $GITHUB_OUTPUT
          fi
      
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mon-s01-e2e-reports-${{ matrix.test_suite.name }}
          path: |
            test-results/
            tests/reports/
          retention-days: 30
      
      - name: Upload Evil Fixtures
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: evil-test-fixtures
          path: |
            tests/fixtures/evil_files/
            tests/fixtures/expected_outputs/
          retention-days: 7
      
      - name: E2E Results Summary
        if: always() && matrix.test_suite.name == 'Core E2E'
        run: |
          echo "## 🧪 MON-S01 E2E Regression Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ steps.parse_results.outputs.total_tests }}" != "0" ]]; then
            echo "| Метрика | Значение |" >> $GITHUB_STEP_SUMMARY
            echo "|---------|----------|" >> $GITHUB_STEP_SUMMARY
            echo "| 🧪 Всего тестов | ${{ steps.parse_results.outputs.total_tests }} |" >> $GITHUB_STEP_SUMMARY
            echo "| ✅ Пройдено | ${{ steps.parse_results.outputs.passed_tests }} |" >> $GITHUB_STEP_SUMMARY
            echo "| ❌ Провалено | ${{ steps.parse_results.outputs.failed_tests }} |" >> $GITHUB_STEP_SUMMARY
            echo "| 📈 Процент успеха | ${{ steps.parse_results.outputs.pass_rate }}% |" >> $GITHUB_STEP_SUMMARY
            echo "| ⏱️ Время выполнения | ${{ steps.parse_results.outputs.duration }}s |" >> $GITHUB_STEP_SUMMARY
            echo "| 🔧 Mock режим | ${{ steps.parse_results.outputs.mock_mode }} |" >> $GITHUB_STEP_SUMMARY
            
            # Статус общий
            if (( $(echo "${{ steps.parse_results.outputs.pass_rate }} >= 80" | bc -l) )); then
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "🎯 **Статус:** ✅ ТЕСТЫ УСПЕШНЫ" >> $GITHUB_STEP_SUMMARY
            elif (( $(echo "${{ steps.parse_results.outputs.pass_rate }} >= 70" | bc -l) )); then
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "⚠️ **Статус:** 🟡 ТЕСТЫ С ЗАМЕЧАНИЯМИ" >> $GITHUB_STEP_SUMMARY
            else
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "❌ **Статус:** 🔴 КРИТИЧЕСКИЕ ПРОБЛЕМЫ" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "❌ E2E тесты не выполнились корректно" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📄 Подробные отчеты доступны в артефактах билда." >> $GITHUB_STEP_SUMMARY
      
      - name: Evaluate Test Results
        if: always() && matrix.test_suite.name == 'Core E2E'
        run: |
          # Определяем успешность на основе результатов
          PASS_RATE="${{ steps.parse_results.outputs.pass_rate }}"
          FAILED_TESTS="${{ steps.parse_results.outputs.failed_tests }}"
          E2E_EXIT_CODE="${{ steps.e2e_tests.outputs.e2e_exit_code }}"
          
          echo "Анализ результатов:"
          echo "  Pass rate: $PASS_RATE%"
          echo "  Failed tests: $FAILED_TESTS"
          echo "  E2E exit code: $E2E_EXIT_CODE"
          
          # Критерии успеха:
          # 1. Pass rate >= 80% = успех
          # 2. Pass rate >= 70% = предупреждение (не блокируем)
          # 3. Pass rate < 70% = провал
          
          if [[ "$PASS_RATE" == "0" ]] || [[ -z "$PASS_RATE" ]]; then
            echo "❌ E2E тесты полностью провалились"
            exit 1
          elif (( $(echo "$PASS_RATE >= 80" | bc -l) )); then
            echo "✅ E2E тесты успешны ($PASS_RATE%)"
            exit 0
          elif (( $(echo "$PASS_RATE >= 70" | bc -l) )); then
            echo "⚠️ E2E тесты с замечаниями ($PASS_RATE%) - не блокируем"
            exit 0
          else
            echo "❌ E2E тесты с критическими проблемами ($PASS_RATE%)"
            exit 1
          fi
      
      - name: Comment PR (if applicable)
        if: always() && github.event_name == 'pull_request' && matrix.test_suite.name == 'Core E2E'
        uses: actions/github-script@v6
        with:
          script: |
            const passRate = "${{ steps.parse_results.outputs.pass_rate }}";
            const totalTests = "${{ steps.parse_results.outputs.total_tests }}";
            const passedTests = "${{ steps.parse_results.outputs.passed_tests }}";
            const failedTests = "${{ steps.parse_results.outputs.failed_tests }}";
            const duration = "${{ steps.parse_results.outputs.duration }}";
            const mockMode = "${{ steps.parse_results.outputs.mock_mode }}";
            
            let statusEmoji = "✅";
            let statusText = "УСПЕШНО";
            if (parseFloat(passRate) < 80) {
              statusEmoji = "⚠️";
              statusText = "С ЗАМЕЧАНИЯМИ";
            }
            if (parseFloat(passRate) < 70) {
              statusEmoji = "❌";
              statusText = "КРИТИЧЕСКИЕ ПРОБЛЕМЫ";
            }
            
            const comment = `## 🧪 MON-S01 E2E Regression Results
            
            ${statusEmoji} **Статус:** ${statusText}
            
            | Метрика | Значение |
            |---------|----------|
            | 🧪 Всего тестов | ${totalTests} |
            | ✅ Пройдено | ${passedTests} |
            | ❌ Провалено | ${failedTests} |
            | 📈 Процент успеха | ${passRate}% |
            | ⏱️ Время выполнения | ${duration}s |
            | 🔧 Mock режим | ${mockMode} |
            
            📋 **Тестируемые компоненты:** Полный pipeline обработки файлов
            📄 Подробные отчеты доступны в артефактах билда.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  # Дополнительный job для уведомлений при критических провалах
  notify-on-failure:
    name: 'Notify on Critical Failure'
    runs-on: ubuntu-latest
    needs: mon-s01-e2e-regression
    if: failure() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
      - name: Notify Critical E2E Failure
        run: |
          echo "🚨 КРИТИЧЕСКИЙ ПРОВАЛ MON-S01 E2E ТЕСТОВ"
          echo "Ветка: ${{ github.ref }}"
          echo "Коммит: ${{ github.sha }}"
          echo "Автор: ${{ github.actor }}"
          
          # Здесь можно добавить уведомления в Slack/Teams/Email
          # curl -X POST -H 'Content-type: application/json' \
          #   --data '{"text":"🚨 MON-S01 E2E Tests FAILED on ${{ github.ref }}"}' \
          #   ${{ secrets.SLACK_WEBHOOK_URL }}

  # Job для публикации метрик в случае успеха
  publish-metrics:
    name: 'Publish E2E Metrics'
    runs-on: ubuntu-latest
    needs: mon-s01-e2e-regression
    if: success() && github.ref == 'refs/heads/main'
    
    steps:
      - name: Publish Success Metrics
        run: |
          echo "📊 Публикация метрик MON-S01 E2E"
          echo "✅ E2E тесты успешно пройдены на main ветке"
          
          # Здесь можно интегрироваться с системами мониторинга
          # curl -X POST "https://metrics.company.com/api/mon-s01" \
          #   -H "Authorization: Bearer ${{ secrets.METRICS_TOKEN }}" \
          #   -d '{"status": "success", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' 